### ISSUE TITLE
satisfactory

### ISSUE THREAD

**Issue by zeratax** [matejc/helper_scripts#1]
First off thank you very much for this script ^^

This current iteration seems to have an issue though:

https://github.com/matejc/helper_scripts/blob/7cd77bf0767196d4f652e4eb595939f5f635d365/nixes/satisfactory.nix#L23-L24
seems like these two arguments need to be swapped? that's at least what the steamcmd tells me and that fixes it.

would also be nice to add an option to swap between public and experimental branch.
so adding  `-beta experimental` or `-beta public`
see https://satisfactory.fandom.com/wiki/Dedicated_servers#Experimental_branch_selection

Also would ofc be amazing if you could decoratively set the config files (specifically the player limit), but not sure how much work that would be.

I wonder if this would make for a good pr for the main nixpkgs repo...

**Comment by matejc** [comment]
I made an update, please check the master branch.
I already downscaled my server, so maybe for the next major update of Satisfactory (or at the time that I will again start playing), I can upscale it again and make some more improvements to the NixOS module, but for now this is it from me.

**Comment by jacob-swanson** [comment]
FYI there are a couple changes to make it compatible with update 8.

1. Change `UE4Server-Linux-Shipping` to `UnrealServer-Linux-Shipping`.
2. Add `-multihome=0.0.0.0` after `FactoryGame`, since it binds only to ipv6 by default for some reason now.

**Comment by matejc** [comment]
I guess we can close this one now
